# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables :
  tag : '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs :
    - job :
      displayName: 'Build Job'
      pool:
        name: Default
        demands:
        - agent.name -equals SRINIVAS

      steps :
      # Task-1: Build Docker Image and push to Azure Container Registry ACR
      - task: Docker@2
        inputs:
          containerRegistry: 'SC-azure-container-registry'
          repository: 'custom2aksnginxapp1'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'

      # Task-2: Copy kube-manifest files to Build Artifact Directory
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(agent.builddirectory)'
          Contents: '*manifests*'
          TargetFolder: '$(build.artifactstagingdirectory)'
          OverWrite: true

      # Task-3: Publish build articats to Azure Pipelines
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'kube-manifests'
          publishLocation: 'Container'
